# Site settings
---
layout: post
title: Cda's 博客
navi_item_title: 元婴
navi_item_tech: 技术
navi_item_read: 阅读
navi_item_life: 生活
navi_item_else: 其他

baseurl: /LetronBlog
paginate: 10
---

# Build settings
markdown: kramdown
